name: Release

on:
  push: 
    tags: 
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build info
      id: build_info
      run: |
        BUILD_TAG=${GITHUB_REF#refs/tags/}
        cat ./CHANGELOG.md | grep "$BUILD_TAG" | sed 's%^\*[[:space:]]*\*\*[0-9.]*\*\*[[:space:]]*%%g' > ${{ github.workspace }}-CHANGELOG.txt
        echo "::set-output name=build_tag::${BUILD_TAG}"

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Build
      run: ./gradlew check buildPlugin

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        draft: false
        prerelease: false
        files:
          build/distributions/CheckStyle-IDEA-${{ steps.build_info.outputs.build_tag }}.zip

    - name: Publish to Jetbrains Plugin Repo
      run: ./gradlew publishPlugin
      env:
        JETBRAINS_PLUGIN_REPO_TOKEN: ${{ secrets.JETBRAINS_PLUGIN_REPO_TOKEN }}
